# /// script
# requires-python = ">=3.12,<3.13"
# dependencies = ["pandas==2.3.3", "openpyxl", "numpy==2.2.6", "matplotlib==3.10.8"]
# ///
"""GOALS 1 — is the slip angle in the Wang database measured or computed?

Part A  searches every column the IC did not use for a match with atan2(vy, vx) (rad, deg, ±)
        and the small-angle ratio vy/vx, using the IC's own outputs (cols 17, 18).
Part B  cross-checks the two slip-angle columns (3 raw, 19 smooth) against BOTH velocity pairs
        (9/10 raw, 17/18 smooth) to establish which was derived from which.
Part C  low-speed behaviour (atan2 ill-conditioned).
Part D  kinematic bicycle-model consistency of the dvx/dvy columns (sign convention, which a_x/a_y).

Writes docs/slip_angle_provenance.md and one figure per track under docs/fig/.
Run from the repo root: `uv run scripts/check_slip_angle.py`.
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib
import numpy as np
import pandas as pd

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "Database"
DOC = ROOT / "docs" / "slip_angle_provenance.md"
FIG_DIR = ROOT / "docs" / "fig"

TRACKS = {"wang21": "train", "wang22": "val", "wang31": "testA", "wang81": "testB", "wang32": "testC"}

# Column legend from the original MATLAB export script (0-based, as pd.read_excel(header=None) sees it).
COLS = {
    0: "t",
    1: "acc_x",
    2: "acc_y",
    3: "Sideslip_angle",
    4: "St_angle",
    5: "wspeed1",
    6: "wspeed2",
    7: "wspeed3",
    8: "wspeed4",
    9: "vx",
    10: "vy",
    11: "YawRate",
    12: "ay_true",
    13: "ax_true",
    14: "ax_nobias",
    15: "vy_smooth",
    16: "YawRate_smooth",
    17: "vy_smooth",
    18: "vx_smooth",
    19: "SA_smooth",
    20: "dvx",
    21: "dvy",
    22: "wspeedfront",
    23: "wspeedrear",
}
VX_COL, VY_COL = 18, 17  # IC outputs y1, y2
VX_RAW, VY_RAW = 9, 10  # raw velocity pair
SA_RAW, SA_SMOOTH = 3, 19  # slip-angle columns (raw is in degrees, smooth in rad)
IC_COLS = {0, 2, 11, 14, 17, 18, 22, 23}  # time + the 7 columns the IC used
TOL_RAD = 1e-3  # Part A rule: "computed" if max|Δ| below this on every track (≈ 0.06°)
EXACT = 1e-9  # Part B rule: floating-point identity
SMOOTH_WIN = 21  # samples (≈ 100 ms at 200 Hz) — best-fitting moving-average window for col 19
LOW_SPEED = 0.5  # m/s — atan2 ill-conditioned below this

QUESTION = (
    "**Question.** For each of the 5 Wang tracks, does any column equal `atan2(vy, vx)` (rad or deg, ±sign) "
    "to within floating-point/rounding tolerance? If yes → SA is *computed* from vx, vy and carries no "
    "independent information. If the closest column differs by more than sensor-noise level → SA is "
    "*measured* (GPS/INS) and is a legitimate independent third output."
)


def load(track: str) -> pd.DataFrame:
    path = DATA_DIR / f"{track}dv_bic_MGGP.xlsx"
    if not path.exists():
        sys.exit(f"missing {path} — copy the Wang .xlsx files into {DATA_DIR}")
    return pd.read_excel(path, header=None)


def candidates(vx: np.ndarray, vy: np.ndarray) -> dict[str, np.ndarray]:
    beta = np.arctan2(vy, vx)
    with np.errstate(divide="ignore", invalid="ignore"):
        ratio = np.where(np.abs(vx) > 1e-9, vy / vx, np.nan)
    c = {"atan2_rad": beta, "atan2_deg": np.degrees(beta), "vy/vx": ratio}
    c.update({f"-{k}": -v for k, v in list(c.items())})
    return c


def stats(a: np.ndarray, b: np.ndarray) -> dict[str, float]:
    m = np.isfinite(a) & np.isfinite(b)
    d = a[m] - b[m]
    r = float(np.corrcoef(a[m], b[m])[0, 1]) if a[m].std() > 0 and b[m].std() > 0 else float("nan")
    return {"rmse": float(np.sqrt(np.mean(d**2))), "max": float(np.max(np.abs(d))), "mean": float(d.mean()), "r": r}


def movavg(x: np.ndarray, w: int) -> np.ndarray:
    return pd.Series(x).rolling(w, center=True, min_periods=1).mean().to_numpy()


def fmt(s: dict[str, float]) -> str:
    return f"rmse {s['rmse']:.1e} · max {s['max']:.1e} · mean {s['mean']:+.1e} · r {s['r']:.5f}"


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")  # Windows consoles default to cp1252
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    L = [
        QUESTION,
        "",
        "# Slip-angle provenance — Wang/Jilin tracks",
        "",
        "Generated by `scripts/check_slip_angle.py`. Column names follow the original MATLAB export legend "
        "(see `docs/column_inventory.md`). Two slip-angle columns exist: **col 3 `Sideslip_angle`** (raw, degrees) "
        "and **col 19 `SA_smooth`** (rad). Two velocity pairs exist: raw (9, 10) and smooth (18, 17 — the IC's outputs).",
        "",
    ]

    partA: list[dict] = []
    partB: list[str] = []
    partC: list[str] = []
    partD: list[str] = []
    sa_raw_exact_tracks = 0
    sa_smooth_is_filtered = True

    for track, role in TRACKS.items():
        df = load(track)
        t = df[0].to_numpy()
        vx, vy = df[VX_COL].to_numpy(), df[VY_COL].to_numpy()
        vx9, vy10 = df[VX_RAW].to_numpy(), df[VY_RAW].to_numpy()
        sa3 = np.radians(df[SA_RAW].to_numpy())
        sa19 = df[SA_SMOOTH].to_numpy()
        cands = candidates(vx, vy)

        # ---- Part A: blind search over non-IC columns vs candidates from the IC's own outputs.
        rows = [
            (c, name, *stats(df[c].to_numpy(), cand).values())
            for c in df.columns
            if c not in IC_COLS
            for name, cand in cands.items()
        ]
        table = pd.DataFrame(rows, columns=["col", "candidate", "rmse", "max", "mean", "r"])
        best = table.sort_values(["max", "rmse"]).iloc[0]
        partA.append({"track": track, **best.to_dict()})
        print(
            f"=== {track} ({role}) Part A best: col {int(best.col)} {COLS[int(best.col)]} vs {best.candidate} — "
            f"RMSE {best.rmse:.2e}, max|Δ| {best['max']:.2e}, r {best.r:.5f}"
        )

        # ---- Part B: which slip-angle column came from which velocity pair?
        b_raw = stats(sa3, np.arctan2(vy10, vx9))
        b_vy = stats(vy10, vx9 * np.tan(sa3))
        b_sm_filt = stats(sa19, movavg(sa3, SMOOTH_WIN))
        b_sm_ic = stats(sa19, np.arctan2(vy, vx))
        b_off_vy = stats(vy, vx * np.tan(sa19))  # constant ⇒ vy_smooth carries an offset vs SA_smooth
        b_off_vx = stats(vx, movavg(vx9, 101))
        sa_raw_exact_tracks += b_raw["max"] < EXACT
        sa_smooth_is_filtered &= b_sm_filt["r"] > 0.999
        partB += [
            f"| {track} | {fmt(b_raw)} | {fmt(b_vy)} | {fmt(b_sm_filt)} | {fmt(b_sm_ic)} | "
            f"{b_off_vy['mean']:+.3f} | {b_off_vx['mean']:+.3f} |"
        ]

        # ---- Part C: low-speed behaviour.
        slow = np.abs(vx) < LOW_SPEED
        n_slow = int(slow.sum())
        desc = (
            f"col 19 there: min {sa19[slow].min():.4g}, max {sa19[slow].max():.4g}, NaN {int(np.isnan(sa19[slow]).sum())}"
            if n_slow
            else f"min v_x = {np.abs(vx).min():.3f} m/s — never below threshold"
        )
        partC.append(f"| {track} | {n_slow} | {desc} |")

        # ---- Part D: bicycle-model consistency of dvx / dvy.
        r11 = df[11].to_numpy()
        dvx, dvy = df[20].to_numpy(), df[21].to_numpy()
        ax14, ax13, ay2, ay12 = (df[c].to_numpy() for c in (14, 13, 2, 12))
        dt = float(np.median(np.diff(t)))
        d = {
            "dvx=d(vx_smooth)/dt": stats(dvx, np.gradient(vx, dt))["r"],
            "dvy=d(vy_smooth)/dt": stats(dvy, np.gradient(vy, dt))["r"],
            "dvx~ax_nobias(14)+r·vy": stats(dvx, ax14 + r11 * vy)["r"],
            "dvx~ax_true(13)+r·vy": stats(dvx, ax13 + r11 * vy)["r"],
            "dvy~acc_y(2)−r·vx": stats(dvy, ay2 - r11 * vx)["r"],
            "dvy~acc_y(2)+r·vx": stats(dvy, ay2 + r11 * vx)["r"],
            "dvy~ay_true(12)+r·vx": stats(dvy, ay12 + r11 * vx)["r"],
        }
        partD.append(f"| {track} | " + " | ".join(f"{v:+.3f}" for v in d.values()) + " |")
        d_keys = list(d)

        # ---- Figure: the three slip-angle sources + residuals vs the IC pair.
        fig, (a1, a2) = plt.subplots(2, 1, figsize=(11, 6.5), sharex=True, gridspec_kw={"height_ratios": [3, 1.3]})
        a1.plot(t, np.arctan2(vy, vx), lw=1.0, label="atan2(vy_smooth 17, vx_smooth 18)  [IC outputs]")
        a1.plot(t, np.arctan2(vy10, vx9), lw=0.6, alpha=0.6, label="atan2(vy 10, vx 9)  [raw pair]")
        a1.plot(t, sa19, lw=0.9, ls="--", label="col 19 SA_smooth")
        a1.set_ylabel("slip angle [rad]")
        a1.legend(loc="best", fontsize=8)
        a1.set_title(f"{track} ({role})")
        a2.plot(t, sa19 - np.arctan2(vy, vx), lw=0.7, color="k", label="col 19 − atan2(17,18)")
        a2.plot(t, sa19 - np.arctan2(vy10, vx9), lw=0.7, color="tab:red", alpha=0.7, label="col 19 − atan2(10,9)")
        a2.set_ylabel("residual [rad]")
        a2.set_xlabel("time [s]")
        a2.legend(loc="best", fontsize=8)
        fig.tight_layout()
        out = FIG_DIR / f"slip_angle_overlay_{track}.png"
        fig.savefig(out, dpi=110)
        plt.close(fig)

    # ---- Assemble the document.
    L += [
        "## Part A — blind search: best match to atan2 of the IC outputs (cols 17, 18)",
        "",
        "| track | col | name | candidate | RMSE | max abs Δ | mean Δ | r |",
        "|---|---:|---|---|---:|---:|---:|---:|",
    ]
    L += [
        f"| {b['track']} | {int(b['col'])} | {COLS[int(b['col'])]} | {b['candidate']} | {b['rmse']:.2e} | "
        f"{b['max']:.2e} | {b['mean']:+.2e} | {b['r']:.5f} |"
        for b in partA
    ]
    worstA = max(b["max"] for b in partA)
    L += [
        "",
        f"Col 19 is the best match on every track, but max|Δ| reaches {worstA:.2e} rad "
        f"(rule: < {TOL_RAD:g} ⇒ computed), so **by Part A alone the verdict would be *measured***. "
        "Part B shows why that reading is wrong.",
        "",
    ]

    L += [
        "## Part B — source cross-check",
        "",
        "| track | col 3 (rad) vs atan2(vy 10, vx 9) | vy 10 vs vx 9·tan(col 3) | col 19 vs movavg(col 3, "
        f"{SMOOTH_WIN}) | col 19 vs atan2(vy 17, vx 18) | mean(vy 17 − vx 18·tan(col 19)) [m/s] | "
        "mean(vx 18 − movavg(vx 9)) [m/s] |",
        "|---|---|---|---|---|---:|---:|",
        *partB,
        "",
        "Reading:",
        "",
        f"- **col 3 `Sideslip_angle` = atan2(vy 10, vx 9) to floating-point precision on {sa_raw_exact_tracks}/5 tracks** "
        "(and vy 10 = vx 9·tan(col 3) likewise). The raw slip angle and the raw velocity pair are the *same information* — "
        "one was derived from the other inside the GPS/INS post-processing. On wang81 the identity holds up to a constant "
        "+0.370 m/s added to vy 10.",
        f"- **col 19 `SA_smooth` is a low-pass of col 3** (≈ {SMOOTH_WIN}-sample moving average, r > 0.999 on all tracks). "
        "It was *not* recomputed from the smooth velocity pair.",
        "- The mismatch between col 19 and atan2(vy 17, vx 18) on wang31 / wang81 / wang32 is a **constant offset in vy_smooth "
        "of ≈ +0.30 to +0.37 m/s** (last-but-one column: RMSE ≈ |mean|, r ≈ 1). A constant δ in vy produces a residual "
        "≈ δ / vx, which is the slow, 1/vx-shaped curve in the figures — not sensor noise. Whoever bias-corrected `vy_smooth` "
        "on those three tracks did not recompute `SA_smooth`. wang21 / wang22 carry no such offset (≈ 0.001–0.002 m/s).",
        "- `vx_smooth` also differs from the raw `vx` by a track-specific constant (last column), i.e. the *_smooth columns "
        "were individually offset-corrected per track.",
        "",
    ]

    L += [
        "## Part C — low-speed behaviour",
        "",
        f"Samples with |v_x| < {LOW_SPEED} m/s (atan2 ill-conditioned):",
        "",
        "| track | count | col 19 behaviour |",
        "|---|---:|---|",
        *partC,
        "",
        "No track ever drops below the threshold (minimum v_x is 1.10 m/s on wang21, ≥ 3.4 m/s elsewhere), so the "
        "standstill singularity of atan2 does not occur in this database. It still has to be guarded in any deployed "
        "estimator.",
        "",
    ]

    L += [
        "## Part D — kinematic bicycle-model consistency (Pearson r)",
        "",
        "`dvx`/`dvy` (cols 20, 21) are the numerical derivatives of the smooth velocities. Which acceleration column and "
        "which sign close `dv_x/dt = a_x + ψ̇ v_y`, `dv_y/dt = a_y − ψ̇ v_x`?",
        "",
        "| track | " + " | ".join(d_keys) + " |",
        "|---|" + "---:|" * len(d_keys),
        *partD,
        "",
        "Reading (outside GOALS 1's question, recorded because it affects GOALS 3 and the IC's physical interpretation):",
        "",
        "- `dvx ≈ ax_true(13) + ψ̇·vy` (r ≈ 0.92–0.94) and `dvy ≈ ay_true(12) + ψ̇·vx` (r ≈ 0.98–0.99). "
        "In this database's sign convention the lateral equation closes with **+ψ̇·v_x**, i.e. `acc_y`/`ay_true` are "
        "recorded with the opposite sign to the textbook body-frame convention (or ψ̇ is). `a_y` and `ψ̇·v_x` correlate "
        "at r ≈ −0.87 to −0.94.",
        "- The IC used the *raw* accelerations (cols 2, 14) as inputs; the model closes far better with the *true* ones "
        "(cols 12, 13): r 0.75 → 0.99 for dvy, 0.79 → 0.94 for dvx. **Input choice is worth revisiting with the advisor "
        "before GOALS 3 fixes the 5-input set.**",
        "",
    ]

    computed = sa_raw_exact_tracks >= 4 and sa_smooth_is_filtered
    verdict = "computed" if computed else "measured/independent"
    L += [
        "## Verdict",
        "",
        f"- **Verdict: {verdict}** — SA column: **19** (`SA_smooth`, rad) for the smoothed signal; **3** (`Sideslip_angle`, deg) raw.",
        "- The raw slip angle is `atan2(vy, vx)` of the raw velocity pair to 1e-16 on 4/5 tracks (wang81: same, after a "
        "+0.370 m/s constant on vy). The smooth slip angle is a ~100 ms moving average of the raw one. **Neither column "
        "carries information that is not already in (vx, vy).**",
        "- Relative to the IC's own outputs (cols 17, 18) the SA column is *inconsistent* on three of five tracks by a "
        "constant vy offset of 0.30–0.37 m/s. Training a 5×3 model on col 19 as-is would force it to learn a per-track "
        "sensor artefact that is not predictable from the inputs.",
        "",
        "### Consequence for GOALS 3",
        "",
        "- Define the third output as **β := atan2(vy 17, vx 18)** (consistent with y1, y2), *not* as col 19. "
        "Then arm B (5×3 MIMO) vs arm A (5×2 + post-hoc atan2) tests exactly one hypothesis: whether fitting β jointly "
        "regularises the vx/vy structure. Any gain cannot come from new measurements, because there are none.",
        "- Report RMSE_β against that same definition; optionally also against col 19 for wang21/wang22 only "
        "(the two tracks where the offset is negligible).",
        "- `(manual)` Ask the advisor / Jilin contact why `vy_smooth` was offset on wang31/81/32 and whether the raw or the "
        "smooth pair is the trustworthy reference — this also affects the IC's reported RMSE on those tracks.",
        "",
    ]
    L += ["## Figures", ""] + [f"![{tr}](fig/slip_angle_overlay_{tr}.png)\n" for tr in TRACKS]

    DOC.parent.mkdir(parents=True, exist_ok=True)
    DOC.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(
        f"\nVERDICT: {verdict} — raw SA exact on {sa_raw_exact_tracks}/5 tracks; col 19 = filtered col 3: {sa_smooth_is_filtered}"
    )
    print(f"wrote {DOC.relative_to(ROOT)} and {len(TRACKS)} figures under {FIG_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
