# /// script
# requires-python = ">=3.12,<3.13"
# dependencies = ["pandas==2.3.3", "openpyxl", "numpy==2.2.6"]
# ///
"""GOALS 1 — column inventory of the five Wang tracks.

Prints, per track, every column's index and aggregated stats (min/p05/median/p95/max/mean/std — no raw rows),
flags the 7 columns the IC used, detects duplicate columns, and writes
docs/column_inventory.md.  Run from the repo root: `uv run scripts/inspect_columns.py`.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "Database"
OUT = ROOT / "docs" / "column_inventory.md"

TRACKS = {"wang21": "train", "wang22": "val", "wang31": "testA", "wang81": "testB", "wang32": "testC"}

# Column legend from the original MATLAB export script (0-based, as pd.read_excel(header=None) sees it).
NAMES = {
    0: "t",
    1: "acc_x",
    2: "acc_y",
    3: "Sideslip_angle",
    4: "St_angle",
    5: "wspeed1",
    6: "wspeed2",
    7: "wspeed3",
    8: "wspeed4",
    9: "vx",
    10: "vy",
    11: "YawRate",
    12: "ay_true",
    13: "ax_true",
    14: "ax_nobias",
    15: "vy_smooth",
    16: "YawRate_smooth",
    17: "vy_smooth",
    18: "vx_smooth",
    19: "SA_smooth",
    20: "dvx",
    21: "dvy",
    22: "wspeedfront",
    23: "wspeedrear",
}
# Roles the IC notebook (TrainingMGGP_LOOP.ipynb) hard-coded.
KNOWN = {
    14: "u1 = a_x",
    2: "u2 = a_y",
    22: "u3 = front wheel",
    23: "u4 = rear wheel",
    11: "u5 = yaw rate",
    18: "y1 = v_x",
    17: "y2 = v_y",
}


def load(track: str) -> pd.DataFrame:
    path = DATA_DIR / f"{track}dv_bic_MGGP.xlsx"
    if not path.exists():
        sys.exit(f"missing {path} — copy the Wang .xlsx files into {DATA_DIR}")
    return pd.read_excel(path, header=None)


def duplicates(df: pd.DataFrame, atol: float = 1e-9) -> list[tuple[int, int]]:
    pairs = []
    cols = list(df.columns)
    for i, a in enumerate(cols):
        for b in cols[i + 1 :]:
            if np.allclose(df[a].to_numpy(), df[b].to_numpy(), atol=atol, equal_nan=True):
                pairs.append((a, b))
    return pairs


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")  # Windows consoles default to cp1252
    lines = [
        "# Column inventory — Wang/Jilin tracks",
        "",
        "Generated by `scripts/inspect_columns.py`. `pd.read_excel(path, header=None)`; all cells float64, no header row.",
        "Names come from the original MATLAB export legend; the **IC role** column marks what `TrainingMGGP_LOOP.ipynb` used "
        "(`u = [14, 2, 22, 23, 11]`, `vx = 18`, `vy = 17`). Units: col 3 in degrees, col 19 in rad, wheel speeds in rad/s (see sanity line).",
        "",
    ]
    for track, role in TRACKS.items():
        df = load(track)
        t = df[0].to_numpy()
        dt = np.diff(t)
        n = len(df)
        print(
            f"\n=== {track} ({role}) — shape {df.shape}, duration {t[-1]:.2f} s, "
            f"dt median {np.median(dt) * 1e3:.3f} ms (min {dt.min() * 1e3:.3f}, max {dt.max() * 1e3:.3f})"
        )
        lines += [
            f"## {track} — {role}",
            "",
            f"- rows: **{n}** · columns: {df.shape[1]} · duration: {t[-1]:.2f} s · "
            f"dt median {np.median(dt) * 1e3:.3f} ms (min {dt.min() * 1e3:.3f}, max {dt.max() * 1e3:.3f}) · "
            f"NaN cells: {int(df.isna().sum().sum())}",
            "",
            "| col | name | IC role | min | p05 | median | p95 | max | mean | std |",
            "|---:|---|---|---:|---:|---:|---:|---:|---:|---:|",
        ]
        for c in df.columns:
            s = df[c]
            row = (
                f"| {c} | {NAMES.get(c, '?')} | {KNOWN.get(c, '')} | {s.min():.5g} | {s.quantile(0.05):.5g} "
                f"| {s.median():.5g} | {s.quantile(0.95):.5g} | {s.max():.5g} | {s.mean():.5g} | {s.std():.5g} |"
            )
            lines.append(row)
            print(row)
        dups = duplicates(df)
        dup_txt = ", ".join(f"({a} {NAMES[a]}, {b} {NAMES[b]})" for a, b in dups) or "none"
        lines += ["", f"Identical column pairs (|Δ| < 1e-9 everywhere): {dup_txt}", ""]
        print("identical pairs:", dups)

        # Sanity: the IC columns should have physically plausible magnitudes.
        vx, wr = df[18], df[23]
        ratio = wr.mean() / vx.mean()
        lines += [
            f"Sanity: mean v_x = {vx.mean():.3f} m/s, mean col23 (rear wheel) = {wr.mean():.3f} → "
            f"ratio col23/v_x = {ratio:.3f} ⇒ wheel columns are **not** m/s; "
            f"ratio ≈ 3.33 fits wheel angular speed in rad/s with r_eff = {1 / ratio:.3f} m "
            f"(km/h would give ≈ 3.6).",
            "",
        ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nwrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
